export const ADD_ING = 'ADD_ING';
export const REMOVE_ING = 'REMOVE_ING';

export const GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS_FAILED  = 'GET_INGREDIENTS_FAILED';

export const POST_INGREDIENTS = 'POST_INGREDIENTS';
export const POST_INGREDIENTS_SUCCESS = 'POST_INGREDIENTS_SUCCESS';
export const POST_INGREDIENTS_FAILED = 'POST_INGREDIENTS_FAILED';

export const TRY_SIGN_IN = 'TRY_SIGN_IN';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED';

export const SIGN_OUT = 'SIGN_OUT';

export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const GET_ORDERS_FAILED  = 'GET_ORDERS_FAILED';

export const SET_BUILT = 'SET_BUILT'


